# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fb6b9a44b288d5e32cf92e33dc6dca3c748af853df945c69e2c2333804200044c27b8b662b18761025807b0fdd71c5033bde589728a7e09e172ea4903ae65c2

test:
  secret_key_base: cf992f6bfe2287e804ade4c10aaf1deebbc23caf7e216b0bb3d120e585ca822baba23388e902d5539b2c311047930d2a0ddf596da821b71744c76b9fb5119433

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
